schoolmates_helper/App/urls.py
# _*_ coding: utf-8 _*_
# 开发团队：软件工程第5组
# 开发人员：莨瑾
# 开发时间：2020/3/20 16:15
# 文件名称: urls.py
# 开发工具：PyCharm
from django.urls import path

from App import views

urlpatterns = [
    path('home/', views.home, name='home'),
    path('alltask/', views.alltask, name='alltask'),
    path('alltaskwithparams/<int:typeid>', views.alltask_with_params, name='alltask_with_params'),
    path('alltasksort/<int:typeid>/<slug:typesort1>/<slug:typesort2>/<slug:typesort3>', views.alltask_sort,
         name='alltask_sort'),

    path('task/', views.task, name='task'),
    path('mine/', views.mine, name='mine'),

    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('checkuser/', views.checkuser, name='checkuser'),
    path('checkemail/', views.checkemail, name='checkemail'),
    path('checklogin/', views.checklogin, name='checklogin'),

    path('logout/', views.logout, name='logout'),

    path('activate/', views.activate, name='activate'),

    path('sendemail/', views.sendemail, name='send_email'),

    path('receivetask/', views.receivetask, name='receivetask'),
    path('relievetask/', views.relievetask, name='relievetask'),
    path('relievetask2/', views.relievetask2, name='relievetask2'),
    path('finishtask/', views.finishtask, name='finishtask'),

    path('aboutus/', views.aboutus, name='aboutus'),
    path('callus/', views.callus, name='callus'),

    path('alltaskpublisher/', views.alltaskpublisher, name='alltaskpublisher'),
    path('alltaskpublisherwithparams/<int:typeid>/', views.alltaskpublisher_with_params,
         name='alltaskpublisher_with_params'),
    path('alltaskpublishersort/<int:typeid>/<int:sort_way>/',
         views.alltaskpublisher_sort, name='alltaskpublisher_sort'),

    path('alltaskhunter/', views.alltaskhunter, name='alltaskhunter'),
    path('alltaskhunterwithparams/<int:typeid>/', views.alltaskhunter_with_params,
         name='alltaskhunter_with_params'),
    path('alltaskhuntersort/<int:typeid>/<int:sort_way>/',
         views.alltaskhunter_sort, name='alltaskhunter_sort'),

    path('huntertask/<int:typeid>/<int:sort_way>/', views.huntertask, name='huntertask'),
    path('publishertask/<int:typeid>/<int:sort_way>/', views.publishertask, name='publishertask'),
    path('taskfinished/<int:typeid>/<int:sort_way>/', views.taskfinished, name='taskfinished'),
    path('comment/<int:typeid>/<int:sort_way>/', views.comment, name='comment'),
    path('taskcontent/<int:task_id>/', views.taskcontent, name='taskcontent'),

    path('modifyuser/', views.modifyuser, name='modifyuser'),
    path('modifytask/<int:task_id>/', views.modifytask, name='modifytask'),
]

schoolmates_helper/schoolmates_helper/urls.py
from django.contrib import admin
from django.urls import path, include

from schoolmates_helper import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home),
    path('App/', include(('App.urls', 'App'), namespace='App')),
    path('task_square/', include('tasks_square.urls')),
    path('task_received/', include('task_received.urls')),
    path('hunt/', include(('hunt.urls', 'hunt'), namespace='hunt')),
    path('task_released/', include('task_released.urls')),
]

schoolmates_helper/templates/main/alltask.html
{% extends 'base_main.html' %}

{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'Schoolmateshelper/main/css/alltask.css' %}"
          xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
{% endblock %}



{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/swiper.jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'Schoolmateshelper/user/js/alltask.js' %}"></script>
{% endblock %}

{% block content %}
    <div id="alltask">
        <aside>
            <ul>
                <li>
                    <a href="{% url 'App:alltask' %}">
                        全部任务
                    </a>
                    {% ifequal  typeid   0 %}
                        <span class="yellowSlide"></span>
                    {% endifequal %}
                </li>
                {% for tasktype in tasktypes %}
                    <li>
                        <a href="{% url 'App:alltask_with_params' tasktype.type_id  %}">{{ tasktype.typename }}</a>
                        {% ifequal  tasktype.type_id  typeid %}
                            <span class="yellowSlide"></span>
                        {% endifequal %}
                    </li>
                {% endfor %}
            </ul>
        </aside>

        <section>
            <nav>
                <ul>
                    <li>
                        <span>
                        <div class="btn-group">
                            <button type="button" class="btn btn-success ">{{ sort }}</button>
                            <button type="button" class="btn btn-success dropdown-toggle " data-toggle="dropdown"
                                    aria-haspopup="true" aria-expanded="false">
                                <span class="glyphicon glyphicon-chevron-down"></span>
                            </button>
                            <ul class="dropdown-menu" id="all_sort">
                                <li style="width:5.0rem;margin-bottom: 0.05rem;"><a
                                        href="{% url 'App:alltask_sort' typeid 'task_time' 'task_reward' 'id' %}"
                                        class="list-group-item list-group-item-success" id="截止日期">截止日期</a></li>
                                <li style="width:5.0rem;margin-bottom: 0.05rem"><a
                                        href="{% url 'App:alltask_sort' typeid 'task_reward' 'task_time' 'id' %}"
                                        class="list-group-item list-group-item-success" id="酬劳">酬劳</a></li>
                                <li style="width:5.0rem;"><a
                                        href="{% url 'App:alltask_sort' typeid 'id' 'task_name' 'task_sketch' %}"
                                        class="list-group-item list-group-item-success" id="联系人">综合排序</a></li>
                            </ul>
                        </div>
                        </span>
                    </li>
                </ul>
            </nav>
            <menu>
                <ul>
                    {% for task in task_list %}
                        <li>
                            <a href="{% url 'App:taskcontent'  task.id %}" class="list-group-item">
                                <h4 class="list-group-item-heading" style="color: darkorange;display: inline-block;
                                text-align: center;vertical-align: center;line-height: 0.4rem;font-weight: 800;">
                                    {{ task.task_name }}</h4><!--border: 1px solid orange; border-radius: 1000px;-->
                                <div class="list-group-item-text">
                                    <div style="overflow: hidden;width: 6rem;white-space: nowrap;text-overflow: ellipsis;">
                                        详情：{{ task.task_sketch }}
                                    </div>
                                    <div style="float: left;display: inline">
                                        酬劳：￥{{ task.task_reward }}
                                        <br>
                                        联系人：{{ task.publisher.username }}
                                    </div>

                                    <div style="font-size: 6px;float: left;display: inline;margin-top: 0.5rem">
                                        截止日期：{{ task.task_time }}
                                    </div>
                                </div>
                                <section>
                                    <button type="submit" onclick="on_click_alltask({{ task.id }},{{ is_login }})" >
                                        接受任务
                                    </button>
                                </section>
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </menu>

        </section>
    </div>
{% endblock %}

schoolmates_helper/templates/main/home.html
{% extends 'base_main.html' %}

{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'Schoolmateshelper/main/css/home.css' %}">
{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/swiper.jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'Schoolmateshelper/main/js/home.js' %}"></script>
{% endblock %}

{% block content %}
    <div id="home" style="width:100%;">
        {# 首页顶部轮播 #}
        <div class="swiper-container" id="topSwiper">
            <div class="swiper-wrapper">
                {% for main_wheel in main_wheels %}
                    <div class="swiper-slide">
                        <a href="https://www.sjtu.edu.cn/">
                            <img src="{{ main_wheel.img }}" alt="{{ main_wheel.name }}">
                        </a>
                    </div>
                {% endfor %}

            </div>

            <div class="swiper-pagination"></div>
        </div>
        <br>
        <p align="center" style="font-size:20px;color:#66ccff;font-family: 华文隶书,serif;">Schoolmates Helper 开启你我的便利之路</p>
        <br>
        <a class='' href="{% url 'App:register' %}">
            <button class="btn btn-success btn-block" type="button">注册</button>
        </a>
        <br>
        <a href="{% url 'App:login' %}">
            <button class="btn btn-success btn-block" type="button">登录</button>
        </a>
        <br>
        <br>

        <a href="https://oc.sjtu.edu.cn/login/canvas"
           style="display: inline-block;width: 49%;text-align: center;overflow: hidden;">
            <dl>
                <dt>
                    <span style="display: inline-block;">
                        <img src="/static/img/canvas.png" alt="canvas" style="width: 4rem;height: 4rem;">
                    </span>
                </dt>
                <dd>canvas在线教学平台</dd>
            </dl>
        </a>
        <a href="https://i.sjtu.edu.cn/"
           style="display: inline-block;width: 49%;overflow: hidden;text-align: center;">
            <dl>
                <dt>
                    <span style="display: inline-block;">
                        <img src="/static/img/teach.png" alt="teach"
                             style="width: 4rem;height: 4rem;">
                    </span>
                </dt>
                <dd>上海交大教学信息服务网</dd>
            </dl>
        </a>
        <p align="center" style="font-family: 华文楷体,serif;color: purple;font-size: large;"   >愿你拥有自由而无用的灵魂！</p>
    </div>








{% endblock %}

schoolmates_helper/templates/main/mine.html
{% extends 'base_main.html' %}

{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'Schoolmateshelper/main/css/mine.css' %}">
{% endblock %}



{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'Schoolmateshelper/main/js/mine.js' %}"></script>
{% endblock %}

{% block content %}
    <div id="mine">
        <div class="fixed">
            {% if is_login %}
                {% if icon %}
                    <span>
                    <img class="u_icon" src="{{ icon }}" alt="{{ user.username }}">
                    </span>
                {% else %}
                    <span>
                    <span class="glyphicon glyphicon-user"></span>
                    </span>
                {% endif %}
                <p>{{ user.username }} <a style="font-size:medium;color: black;" href="{% url 'App:modifyuser' %}">修改个人信息</a></p>

                <p>
                    <span class="glyphicon glyphicon-education"></span>
                    {% if user.is_active %}
                        <span style="font-size: 0.5rem">等级:{{ user.rank}} 普通会员</span>
                    {% else %}
                        <span style="font-size: 0.5rem;color: grey" id="not_activate">
                              未激活
                        </span>
                    {% endif %}

                </p>
            {% else %}
                <span>
                    <span class="glyphicon glyphicon-user"></span>
                </span>
                <p id="not_login" style="font-size: 0.4rem">
                    <span class="glyphicon glyphicon-flash"></span>
                    登录
                </p>
                <p>
                    <span class="glyphicon glyphicon-education"></span>
                    <span>等级</span>
                </p>

                <div id="regis">
                    <a href="{% url 'App:register' %}" style="color: white">注册</a>
                </div>
            {% endif %}


            <p style="font-family: 华文行楷,serif;">
                <span class="glyphicon glyphicon-bullhorn"></span>
                <a href="https://www.fudan.edu.cn/"><span>博学而笃志，切问而近思。修个学历带回家！</span></a>
            </p>
        </div>

        <div class="mine">
            <p>
                <span>我发布的任务</span>
                <a href="{% url 'App:alltaskpublisher' %}">查看所有发布任务> </a>
            </p>
            <p>
                <span>我接受的任务</span>
                <a href="{% url 'App:alltaskhunter' %}">查看所有接受任务> </a>
            </p>
            <nav id="nav">
                <ul>
                    <li onclick="window.location.href='/App/huntertask/0/4/'">
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-shopping-cart"></span>
                            </dt>
                            <dd>已接取，待完成</dd>
                        </dl>
                    </li>
                    <li onclick="window.location.href='/App/publishertask/0/4/'">
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-hdd"></span>
                            </dt>
                            <dd>已被接，待完成</dd>
                        </dl>
                    </li>
                </ul>
                <ul>
                    <li onclick="window.location.href='/App/comment/0/4/'">
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-edit"></span>
                            </dt>
                            <dd>待评价</dd>
                        </dl>
                    </li>
                    <li onclick="window.location.href='/App/taskfinished/0/4/'">
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-fire"></span>
                            </dt>
                            <dd>已完成</dd>
                        </dl>
                    </li>
                </ul>
            </nav>
            <menu>
                <ul>
                    <li onclick="window.location.href='/App/callus/'; ">
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-earphone"></span>
                            </dt>
                            <dd>客服/反馈</dd>
                        </dl>
                    </li>
                    <li onclick="window.location.href='/App/aboutus/'">
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-question-sign"></span>
                            </dt>
                            <dd>关于我们</dd>
                        </dl>
                    </li>
                </ul>
            </menu>
            {% if is_login %}
                <p>
                    <a href="{% url 'App:logout' %}">退出当前账号</a>
                </p>
            {% endif %}
        </div>
    </div>
{% endblock %}

schoolmates_helper/templates/main/mine_not_activated.html
{% extends 'base_main.html' %}

{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'Schoolmateshelper/main/css/mine.css' %}">
{% endblock %}



{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'Schoolmateshelper/main/js/mine_not_activated.js' %}"></script>
{% endblock %}

{% block content %}
    <div id="mine">
        <div class="fixed">
            {% if is_login %}
                {% if icon %}
                    <span>
                    <img class="u_icon" src="{{ icon }}" alt="{{ user.username }}">
                    </span>
                {% else %}
                    <span>
                    <span class="glyphicon glyphicon-user"></span>
                    </span>
                {% endif %}
                <p>{{ user.username }}<a style="font-size:medium;color: black;" href="{% url 'App:modifyuser' %}">修改个人信息</a></p>
                <p>
                    <span class="glyphicon glyphicon-education"></span>
                    {% if user.is_active %}
                        <span style="font-size: 0.5rem">等级:{{ user.rank }}正式会员</span>
                    {% else %}
                        <span style="font-size: 0.5rem;color: grey" id="not_activate">
                              等级:{{ user.rank }} 未激活
                        </span>
                    {% endif %}

                </p>
            {% else %}
                <span>
                    <span class="glyphicon glyphicon-user"></span>
                </span>
                <p id="not_login" style="font-size: 0.4rem">
                    <span class="glyphicon glyphicon-flash"></span>
                    登录
                </p>
                <p>
                    <span class="glyphicon glyphicon-education"></span>
                    <span>等级</span>
                </p>

                <div id="regis">
                    <a href="{% url 'App:register' %}" style="color: white">注册</a>
                </div>
            {% endif %}


            <p style="font-family: 华文行楷,serif;" >
                <span class="glyphicon glyphicon-bullhorn"></span>
                <a href="https://www.fudan.edu.cn/"><span>博学而笃志，切问而近思。修个学历带回家！</span></a>
            </p>
        </div>

        <div class="mine">
            <p>
                <span>我发布的任务</span>
                <a href="" onclick="on_click_mine_not_activated()">查看所有发布任务> </a>
            </p>
            <p>
                <span>我接受的任务</span>
                <a href="" onclick="on_click_mine_not_activated()">查看所有接受任务> </a>
            </p>
            <nav id="nav">
                <ul>
                    <li onclick="on_click_mine_not_activated()">
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-shopping-cart"></span>
                            </dt>
                            <dd>已接取，待完成</dd>
                        </dl>
                    </li>
                    <li onclick="on_click_mine_not_activated()">
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-hdd"></span>
                            </dt>
                            <dd>已被接，待完成</dd>
                        </dl>
                    </li>
                </ul>
                <ul>
                    <li onclick="on_click_mine_not_activated()">
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-edit"></span>
                            </dt>
                            <dd>待评价</dd>
                        </dl>
                    </li>
                    <li onclick="on_click_mine_not_activated()">
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-fire"></span>
                            </dt>
                            <dd>已完成</dd>
                        </dl>
                    </li>
                </ul>
            </nav>
            <menu>
                <ul>
                    <li onclick="window.location.href='/App/callus/'; ">
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-earphone"></span>
                            </dt>
                            <dd>客服/反馈</dd>
                        </dl>
                    </li>
                    <li onclick="window.location.href='/App/aboutus'">
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-question-sign"></span>
                            </dt>
                            <dd>关于我们</dd>
                        </dl>
                    </li>
                </ul>
            </menu>
            {% if is_login %}
                <p>
                    <a href="{% url 'App:logout' %}">退出当前账号</a>
                </p>
            {% endif %}
        </div>
    </div>
{% endblock %}

schoolmates_helper/templates/main/mine_not_login.html
{% extends 'base_main.html' %}

{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'Schoolmateshelper/main/css/mine.css' %}">
{% endblock %}



{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'Schoolmateshelper/main/js/mine_not_activated.js' %}"></script>
{% endblock %}

{% block content %}
    <div id="mine">
        <div class="fixed">
            {% if is_login %}
                {% if icon %}
                    <span>
                    <img class="u_icon" src="{{ icon }}" alt="{{ user.username }}">
                    </span>
                {% else %}
                    <span>
                    <span class="glyphicon glyphicon-user"></span>
                    </span>
                {% endif %}
                <p>{{ user.username }}</p>
                <p>
                    <span class="glyphicon glyphicon-education"></span>
                    {% if user.is_active %}
                        <span style="font-size: 0.5rem">正式会员</span>
                    {% else %}
                        <span style="font-size: 0.5rem;color: grey" id="not_activate">
                              未激活
                        </span>
                    {% endif %}

                </p>
            {% else %}
                <span>
                    <span class="glyphicon glyphicon-user"></span>
                </span>
                <p id="not_login" style="font-size: 0.4rem">
                    <span class="glyphicon glyphicon-flash"></span>
                    登录
                </p>
                <p>
                    <span class="glyphicon glyphicon-education"></span>
                    <span>等级</span>
                </p>

                <div id="regis">
                    <a href="{% url 'App:register' %}" style="color: white">注册</a>
                </div>
            {% endif %}


            <p style="font-family: 华文行楷,serif;">
                <span class="glyphicon glyphicon-bullhorn"></span>
                <a href="https://www.fudan.edu.cn/"><span>博学而笃志，切问而近思。修个学历带回家！</span></a>
            </p>
        </div>

        <div class="mine">
            <p>
                <span>我发布的任务</span>
                <a href="" onclick="on_click_mine_not_login()">查看所有发布任务> </a>
            </p>
            <p>
                <span>我接受的任务</span>
                <a href="" onclick="on_click_mine_not_login()">查看所有接受任务> </a>
            </p>
            <nav id="nav">
                <ul>
                    <li onclick="on_click_mine_not_login()">
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-shopping-cart"></span>
                            </dt>
                            <dd>已接取，待完成</dd>
                        </dl>
                    </li>
                    <li onclick="on_click_mine_not_login()">
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-hdd"></span>
                            </dt>
                            <dd>已被接，待完成</dd>
                        </dl>
                    </li>
                </ul>
                <ul>
                    <li onclick="on_click_mine_not_login()">
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-edit"></span>
                            </dt>
                            <dd>待评价</dd>
                        </dl>
                    </li>
                    <li onclick="on_click_mine_not_login()">
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-fire"></span>
                            </dt>
                            <dd>已完成</dd>
                        </dl>
                    </li>
                </ul>
            </nav>
            <menu>
                <ul>
                    <li onclick="window.location.href='/App/callus/'; ">
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-earphone"></span>
                            </dt>
                            <dd>客服/反馈</dd>
                        </dl>
                    </li>
                    <li onclick="window.location.href='/App/aboutus'">
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-question-sign"></span>
                            </dt>
                            <dd>关于我们</dd>
                        </dl>
                    </li>
                </ul>
            </menu>
            {% if is_login %}
                <p>
                    <a href="{% url 'App:logout' %}">退出当前账号</a>
                </p>
            {% endif %}
        </div>
    </div>
{% endblock %}

schoolmates_helper/templates/main/task.html
{% extends 'base_main.html' %}

{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'Schoolmateshelper/main/css/task.css' %}">
{% endblock %}



{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/swiper.jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'Schoolmateshelper/user/js/task.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="container" id="task">
        <form method="post" enctype="multipart/form-data" action="{% url 'App:task' %}" onsubmit="return checktask()" style="height:auto;overflow: auto;padding: 1.5rem 0;">

            {% csrf_token %}

            <div class="form-group">
                <label for="taskname_input">任务名称</label>
                <input type="text" class="form-control" id="taskname_input" placeholder="请输入任务名称" name="taskname">
                <span id="taskname_info"></span>
            </div>
            <div class="form-group">
                <label for="tasktype_input">任务类型</label>
                <select class="form-control" id="tasktype_input" name="tasktype" style="width: 10rem;">
                    <option value=1>快递服务</option>
                    <option value=2>修理服务</option>
                    <option value=3>课业指导</option>
                    <option value=4>邂逅表白</option>
                    <option value=5>其他服务</option>
                </select>
                <span id="tasktype_info"></span>
            </div>

            <div class="form-group">
                <label for="contact_input">你想要透露的联系方式</label>
                <select class="form-control" id="contact_input" name="contact" style="width: 10rem;">
                    <option value=1>email</option>
                    <option value=2>QQ</option>
                    <option value=3>wechat</option>
                    <option value=4>telephone</option>
                    <option value=5>其它联系方式</option>
                </select>
                <span id="contact_info"></span>
            </div>

            <div class="form-group">
                <label for="tasksketch_input">任务简介</label>
                <textarea rows="3" class="form-control" placeholder="请输入任务简介,以简单地描述你的任务(不超过200字)" id="tasksketch_input"
                          name="tasksketch"></textarea>
                <span id="taskskecth_info"></span>
            </div>

            <div class="form-group">
                <label>截止日期</label><br>
                <input type="text" class="form-control" id="taskdate_year_input" placeholder="截至年份" name="taskdate_year"
                       style="width: 2.2rem;display: inline;">
                <label>年</label>
                <span id="taskdate_year_info"></span>
                <input type="text" class="form-control" id="taskdate_month_input" placeholder="截至月份" name="taskdate_month"
                       style="width: 2.2rem;display: inline;">
                <label>月</label>
                <span id="taskdate_month_info"></span>
                <input type="text" class="form-control" id="taskdate_day_input" placeholder="截至日期" name="taskdate_day"
                       style="width: 2.2rem;display: inline;">
                <label>日</label>
                <span id="taskdate_day_info"></span>
            </div>
            <div class="form-group">
                <label>任务酬劳</label><br>
                <input type="text" class="form-control" id="taskreward_input" placeholder="你想给你的委托者多少酬劳呢？" name="taskreward"
                       style="width: 6rem;display: inline;">
                <label>￥</label>
                <br>
                <span id="taskreward_info"></span>
            </div>

            <div class="form-group">
                <label for="taskfile_input">任务附件</label>
                <input type="file" id="taskfile_input" name="taskfile">
                <span id="taskfile_info"></span>
            </div>
            <button type="submit" class="btn btn-block btn-warning">发布任务</button>
        </form>


    </div>
{% endblock %}