schoolmate helper/schoolmates_helper/App/urls.py
# _*_ coding: utf-8 _*_
# 开发团队：软件工程第5组
# 开发人员：莨瑾
# 开发时间：2020/3/20 16:15
# 文件名称: urls.py
# 开发工具：PyCharm
from django.urls import path

from App import views

urlpatterns = [
    path('home/', views.home, name='home'),
    path('alltask/', views.alltask, name='alltask'),
    path('alltaskwithparams/<int:typeid>', views.alltask_with_params, name='alltask_with_params'),
    path('alltasksort/<int:typeid>/<slug:typesort1>/<slug:typesort2>/<slug:typesort3>', views.alltask_sort,
         name='alltask_sort'),

    path('task/', views.task, name='task'),
    path('mine/', views.mine, name='mine'),

    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('checkuser/', views.checkuser, name='checkuser'),
    path('checkemail/', views.checkemail, name='checkemail'),
    path('checklogin/', views.checklogin, name='checklogin'),

    path('logout/', views.logout, name='logout'),

    path('activate/', views.activate, name='activate'),

    path('sendemail/', views.sendemail, name='send_email'),

    path('receivetask/', views.receivetask, name='receivetask'),
    path('relievetask/', views.relievetask, name='relievetask'),
    path('relievetask2/', views.relievetask2, name='relievetask2'),
    path('finishtask/', views.finishtask, name='finishtask'),

    path('aboutus/', views.aboutus, name='aboutus'),
    path('callus/', views.callus, name='callus'),

    path('alltaskpublisher/', views.alltaskpublisher, name='alltaskpublisher'),
    path('alltaskpublisherwithparams/<int:typeid>/', views.alltaskpublisher_with_params,
         name='alltaskpublisher_with_params'),
    path('alltaskpublishersort/<int:typeid>/<int:sort_way>/',
         views.alltaskpublisher_sort, name='alltaskpublisher_sort'),

    path('alltaskhunter/', views.alltaskhunter, name='alltaskhunter'),
    path('alltaskhunterwithparams/<int:typeid>/', views.alltaskhunter_with_params,
         name='alltaskhunter_with_params'),
    path('alltaskhuntersort/<int:typeid>/<int:sort_way>/',
         views.alltaskhunter_sort, name='alltaskhunter_sort'),

    path('huntertask/<int:typeid>/<int:sort_way>/', views.hunertask, name='huntertask'),
    path('publishertask/<int:typeid>/<int:sort_way>/', views.publishertask, name='publishertask'),
    path('taskfinished/<int:typeid>/<int:sort_way>/', views.taskfinished, name='taskfinished'),
    path('comment/<int:typeid>/<int:sort_way>/', views.comment, name='comment'),
    path('taskcontent/<int:task_id>/', views.taskcontent, name='taskcontent'),

    path('modifyuser/', views.modifyuser, name='modifyuser'),
    path('modifytask/<int:task_id>/', views.modifytask, name='modifytask'),
]

schoolmate helper/schoolmates_helper/schoolmates_helper/urls.py
from django.contrib import admin
from django.urls import path, include

from schoolmates_helper import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',views.home),
    path('App/',include(('App.urls','App'),namespace='App')),
]

schoolmate helper/schoolmates_helper/templates/user/alltask_hunter.html
{% extends 'base_main.html' %}

{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'Schoolmateshelper/user/css/alltask_hunter.css' %}"
          xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
{% endblock %}



{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/swiper.jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'Schoolmateshelper/user/js/alltask_hunter.js' %}"></script>

{% endblock %}

{% block content %}
    <div id="alltask">
        <aside>
            <ul>
                <li>
                    <a href="{% url 'App:alltaskhunter' %}">
                        全部任务
                    </a>
                    {% ifequal  typeid   0 %}
                        <span class="yellowSlide"></span>
                    {% endifequal %}
                </li>
                {% for tasktype in tasktypes %}
                    <li>
                        <a href="{% url 'App:alltaskhunter_with_params' tasktype.type_id %}">{{ tasktype.typename }}</a>
                        {% ifequal  tasktype.type_id  typeid %}
                            <span class="yellowSlide"></span>
                        {% endifequal %}
                    </li>
                {% endfor %}
            </ul>
            <a href="{% url 'App:mine' %}" style="font-size: large">
                <span class="glyphicon glyphicon-share-alt" style="color: blue"></span>
                <span style="color: blue">返回</span>
            </a>
        </aside>

        <section>
            <nav>
                <ul>
                    <li>
                        <span>
                        <div class="btn-group">
                            <button type="button" class="btn btn-success ">{{ sort }}</button>
                            <button type="button" class="btn btn-success dropdown-toggle " data-toggle="dropdown"
                                    aria-haspopup="true" aria-expanded="false">
                                <span class="glyphicon glyphicon-chevron-down"></span>
                            </button>
                            <ul class="dropdown-menu" id="all_sort">
                                <li style="width:5.0rem;margin-bottom: 0.05rem;"><a
                                        href="{% url 'App:alltaskhunter_sort' typeid 0 %}"
                                        class="list-group-item list-group-item-success" id="未完成">未完成</a></li>
                                <li style="width:5.0rem;margin-bottom: 0.05rem"><a
                                        href="{% url 'App:alltaskhunter_sort' typeid 1 %}"
                                        class="list-group-item list-group-item-success" id="已完成">已完成</a></li>
                                <li style="width:5.0rem;"><a
                                        href="{% url 'App:alltaskhunter_sort' typeid 4 %}"
                                        class="list-group-item list-group-item-success" id="所有任务">所有任务</a></li>
                            </ul>
                        </div>
                        </span>
                    </li>
                </ul>
            </nav>
            <menu>
                <ul>
                    {% for task in task_list %}
                        <li>
                            <a href="{% url 'App:taskcontent'  task.id %}" class="list-group-item">
                                <h4 class="list-group-item-heading" style="color: darkorange;display: inline-block;
                                text-align: center;vertical-align: center;line-height: 0.4rem;font-weight: 800;">
                                    {{ task.task_name }}</h4><!--border: 1px solid orange; border-radius: 1000px;-->
                                <div class="list-group-item-text">
                                    <div>
                                        详情：{{ task.task_sketch }}
                                    </div>
                                    <div style="float: left;display: inline">
                                        酬劳：￥{{ task.task_reward }}
                                        <br>
                                        联系人：{{ task.publisher.username }}
                                    </div>

                                    <div style="font-size: 6px;float: left;display: inline;margin-top: 0.5rem">
                                        截止日期：{{ task.task_date_year }}年{{ task.task_date_month }}月{{ task.task_date_month }}日
                                    </div>

                                    <div>
                                        {% if task.is_finished %}
                                            <h1 style="color: red;border:1px solid red;border-radius: 1500px;display:inline-block;position: absolute;right: 0.15rem;">
                                                已完成</h1>
                                        {% else %}
                                            <h1 style="color: green;border:1px solid green;border-radius: 1500px;display: inline-block;position: absolute;right: 0.15rem;">
                                                未完成</h1>
                                            <button class="btn-danger" onclick="relievetask2({{ task.id }})" style="position: absolute;right:0.15rem;margin-top: 0.5rem">取消任务</button>
                                        {% endif %}
                                    </div>
                                </div>
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </menu>

        </section>
    </div>
{% endblock %}

schoolmate helper/schoolmates_helper/templates/user/alltask_publisher.html
{% extends 'base_main.html' %}

{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'Schoolmateshelper/user/css/alltask_publisher.css' %}"
          xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
{% endblock %}



{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/swiper.jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'Schoolmateshelper/user/js/alltask_publisher.js' %}"></script>
{% endblock %}

{% block content %}
    <div id="alltask">
        <aside>
            <ul>
                <li>
                    <a href="{% url 'App:alltaskpublisher' %}">
                        全部任务
                    </a>
                    {% ifequal  typeid   0 %}
                        <span class="yellowSlide"></span>
                    {% endifequal %}
                </li>
                {% for tasktype in tasktypes %}
                    <li>
                        <a href="{% url 'App:alltaskpublisher_with_params' tasktype.type_id %}">{{ tasktype.typename }}</a>
                        {% ifequal  tasktype.type_id  typeid %}
                            <span class="yellowSlide"></span>
                        {% endifequal %}
                    </li>
                {% endfor %}
            </ul>
            <a href="{% url 'App:mine' %}" style="font-size: large">
                <span class="glyphicon glyphicon-share-alt" style="color: blue"></span>
                <span style="color: blue">返回</span>
            </a>
        </aside>

        <section>
            <nav>
                <ul>
                    <li>
                        <span>
                        <div class="btn-group">
                            <button type="button" class="btn btn-success ">{{ sort }}</button>
                            <button type="button" class="btn btn-success dropdown-toggle " data-toggle="dropdown"
                                    aria-haspopup="true" aria-expanded="false">
                                <span class="glyphicon glyphicon-chevron-down"></span>
                            </button>
                            <ul class="dropdown-menu" id="all_sort">
                                <li style="width:5.0rem;margin-bottom: 0.05rem;"><a
                                        href="{% url 'App:alltaskpublisher_sort' typeid 0 %}"
                                        class="list-group-item list-group-item-success" id="未被接">未被接</a></li>
                                <li style="width:5.0rem;margin-bottom: 0.05rem"><a
                                        href="{% url 'App:alltaskpublisher_sort' typeid 1 %}"
                                        class="list-group-item list-group-item-success" id="已被接">已被接</a></li>
                                <li style="width:5.0rem;"><a
                                        href="{% url 'App:alltaskpublisher_sort' typeid 4 %}"
                                        class="list-group-item list-group-item-success" id="所有任务">所有任务</a></li>
                            </ul>
                        </div>
                        </span>
                    </li>
                </ul>
            </nav>
            <menu>
                <ul>
                    {% for task in task_list %}
                        <li>
                            <a href="{% url 'App:taskcontent' task.id %}" class="list-group-item">
                                <h4 class="list-group-item-heading" style="color: darkorange;display: inline-block;
                                text-align: center;vertical-align: center;line-height: 0.4rem;font-weight: 800;">
                                    {{ task.task_name }}</h4><!--border: 1px solid orange; border-radius: 1000px;-->
                                <div class="list-group-item-text">
                                    <div>
                                        详情：{{ task.task_sketch }}
                                    </div>
                                    <div style="float: left;display: inline">
                                        酬劳：￥{{ task.task_reward }}
                                        <br>
                                        联系人：{{ task.publisher.username }}
                                    </div>

                                    <div style="font-size: 6px;float: left;display: inline;margin-top: 0.5rem">
                                        截止日期：{{ task.task_date_year }}年{{ task.task_date_month }}月{{ task.task_date_month }}日
                                    </div>

                                    <div>
                                        {% if task.is_pickedup %}
                                            {% if task.is_finished %}
                                                <h1 style="color: green;border:1px solid green;border-radius: 1500px;display:inline-block;position: absolute;right: 0.15rem;">
                                                    已完成</h1>
                                            {% else %}
                                                <h1 style="color: red;border:1px solid red;border-radius: 1500px;display: inline-block;position: absolute;right: 0.15rem;margin-top: -0.5rem;">
                                                    未完成</h1>
                                                <button class="btn-danger" onclick="relievetask({{ task.id }})"
                                                        style="position: absolute;right:0.15rem;">解除委托
                                                </button>
                                                <button class="btn-success" onclick="finishtask({{ task.id }})"
                                                        style="position: absolute;right:0.15rem;margin-top: 0.5rem">任务完成
                                                </button>
                                            {% endif %}

                                        {% else %}
                                            <h1 style="color: green;border:1px solid green;border-radius: 1500px;display: inline-block;position: absolute;right: 0.15rem;">
                                                未被接取</h1>
                                            <button class="btn-success" onclick="modifytask({{ task.id }})"
                                                    style="position:absolute;right:0.15rem;margin-top:0.5rem;">
                                                修改任务
                                            </button>
                                        {% endif %}
                                    </div>
                                </div>
                            </a>
                        </li>

                    {% endfor %}
                </ul>
            </menu>

        </section>
    </div>
{% endblock %}

schoolmate helper/schoolmates_helper/templates/user/huntertask.html
{% extends 'base_main.html' %}

{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'Schoolmateshelper/user/css/alltask_hunter.css' %}"
          xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
{% endblock %}



{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/swiper.jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'Schoolmateshelper/user/js/alltask_hunter.js' %}"></script>
{% endblock %}

{% block content %}
    <div id="alltask">
        <aside>
            <ul>
                <li>
                    <a href="{% url 'App:huntertask' 0 4 %}">
                        全部任务
                    </a>
                    {% ifequal  typeid   0 %}
                        <span class="yellowSlide"></span>
                    {% endifequal %}
                </li>
                {% for tasktype in tasktypes %}
                    <li>
                        <a href="{% url 'App:huntertask' tasktype.type_id 4 %}">{{ tasktype.typename }}</a>
                        {% ifequal  tasktype.type_id  typeid %}
                            <span class="yellowSlide"></span>
                        {% endifequal %}
                    </li>
                {% endfor %}
            </ul>
            <a href="{% url 'App:mine' %}" style="font-size: large">
                <span class="glyphicon glyphicon-share-alt" style="color: blue"></span>
                <span style="color: blue">返回</span>
            </a>
        </aside>

        <section>
            <nav>
                <ul>
                    <li>
                        <span>
                        <div class="btn-group">
                            <button type="button" class="btn btn-success ">{{ sort }}</button>
                            <button type="button" class="btn btn-success dropdown-toggle " data-toggle="dropdown"
                                    aria-haspopup="true" aria-expanded="false">
                                <span class="glyphicon glyphicon-chevron-down"></span>
                            </button>
                            <ul class="dropdown-menu" id="all_sort">
                                <li style="width:5.0rem;margin-bottom: 0.05rem;"><a
                                        href="{% url 'App:huntertask' typeid 0 %}"
                                        class="list-group-item list-group-item-success" id="酬劳">酬劳</a></li>
                                <li style="width:5.0rem;margin-bottom: 0.05rem"><a
                                        href="{% url 'App:huntertask' typeid 1 %}"
                                        class="list-group-item list-group-item-success" id="截止时间">截止时间</a></li>
                                <li style="width:5.0rem;"><a
                                        href="{% url 'App:huntertask' typeid 4 %}"
                                        class="list-group-item list-group-item-success" id="所有任务">所有任务</a></li>
                            </ul>
                        </div>
                        </span>
                    </li>
                </ul>
            </nav>
            <menu>
                <ul>
                    {% for task in task_list %}
                        <li>
                            <a href="{% url 'App:taskcontent'  task.id %}" class="list-group-item">
                                <h4 class="list-group-item-heading" style="color: darkorange;display: inline-block;
                                text-align: center;vertical-align: center;line-height: 0.4rem;font-weight: 800;">
                                    {{ task.task_name }}</h4><!--border: 1px solid orange; border-radius: 1000px;-->
                                <div class="list-group-item-text">
                                    <div>
                                        详情：{{ task.task_sketch }}
                                    </div>
                                    <div style="float: left;display: inline">
                                        酬劳：￥{{ task.task_reward }}
                                        <br>
                                        联系人：{{ task.publisher.username }}
                                    </div>

                                    <div style="font-size: 6px;float: left;display: inline;margin-top: 0.5rem">
                                        截止日期：{{ task.task_date_year }}年{{ task.task_date_month }}月{{ task.task_date_month }}日
                                    </div>

                                    <div>
                                        {% if task.is_finished %}
                                            <h1 style="color: red;border:1px solid red;border-radius: 1500px;display:inline-block;position: absolute;right: 0.15rem;">
                                                已完成</h1>
                                        {% else %}
                                            <h1 style="color: green;border:1px solid green;border-radius: 1500px;display: inline-block;position: absolute;right: 0.15rem;">
                                                未完成</h1>
                                            <button class="btn-danger" onclick="relievetask2({{ task.id }})" style="position: absolute;right:0.15rem;margin-top: 0.5rem">取消任务</button>
                                        {% endif %}
                                    </div>
                                </div>
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </menu>

        </section>
    </div>
{% endblock %}

schoolmate helper/schoolmates_helper/templates/user/modifyuser.html
{% extends 'base_main.html' %}

{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'Schoolmateshelper/main/css/mine.css' %}">
{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'Schoolmateshelper/user/js/modifyuser.js' %}">
    </script>
{% endblock %}

{% block content %}
    <div class="container" style="position:relative;padding: 1.6rem 0;">
        <form method="post" enctype="multipart/form-data" action="{% url 'App:modifyuser' %}" onsubmit="return check()">

            {% csrf_token %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">用户名</h3>
                </div>
                <div class="panel-body">
                    {{ user.username }}
                </div>
            </div>
            <div class="form-group">
                <label for="username_input">新用户名</label>
                <input type="text" class="form-control" id="username_input" placeholder="{{ user.username }}"
                       name="username">
                <span id="username_info"></span>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">交大邮箱</h3>
                </div>
                <div class="panel-body">
                    {{ user.email }}
                </div>
            </div>
            <div class="form-group">
                <label for="email_input">新邮箱</label>
                <input type="email" class="form-control" id="email_input" placeholder="{{ user.email }}" name="email">
                <span id="email_info"></span>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">原密码</h3>
                </div>
                <div class="panel-body">
                    {{ user.password }}
                </div>
            </div>
            <div class="form-group">
                <label for="password_input">新密码</label>
                <input type="password" class="form-control" id="password_input" placeholder="{{ user.password }}"
                       name="password">
                <span id="password_info"></span>
            </div>
            <div class="form-group">
                <label for="password_confirm_input">确认密码</label>
                <input type="password" class="form-control" id="password_confirm_input"
                       placeholder="{{ user.password }}"
                       name="password_confirm">
                <span id="password_confirm_info"></span>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">原头像</h3>
                </div>
                <span class="panel-body">
                    <img style="width: 2rem;height: 2rem;border-radius: 50%;" src="/static/uploads/{{ user.icon }}" alt="{{ user.username }}">
                </span>
            </div>

            <div class="form-group">
                <label for="icon_input">新头像</label>
                <input type="file" id="icon_input" name="icon">
                <span id="icon_info"></span>
            </div>

            <button type="submit" class="btn btn-success btn-block">确认修改</button>

        </form>
        <a href="{% url 'App:mine' %}" style="font-size: large">
            <span class="glyphicon glyphicon-share-alt" style="color: blue"></span>
            <span style="color: blue">返回</span>
        </a>
    </div>
{% endblock %}

schoolmate helper/schoolmates_helper/templates/user/publishertask.html
{% extends 'base_main.html' %}

{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'Schoolmateshelper/user/css/alltask_hunter.css' %}"
          xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
{% endblock %}



{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/swiper.jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'Schoolmateshelper/user/js/alltask_publisher.js' %}"></script>
{% endblock %}

{% block content %}
    <div id="alltask">
        <aside>
            <ul>
                <li>
                    <a href="{% url 'App:publishertask' 0 4 %}">
                        全部任务
                    </a>
                    {% ifequal  typeid   0 %}
                        <span class="yellowSlide"></span>
                    {% endifequal %}
                </li>
                {% for tasktype in tasktypes %}
                    <li>
                        <a href="{% url 'App:publishertask' tasktype.type_id 4 %}">{{ tasktype.typename }}</a>
                        {% ifequal  tasktype.type_id  typeid %}
                            <span class="yellowSlide"></span>
                        {% endifequal %}
                    </li>
                {% endfor %}
            </ul>
            <a href="{% url 'App:mine' %}" style="font-size: large">
                <span class="glyphicon glyphicon-share-alt" style="color: blue"></span>
                <span style="color: blue">返回</span>
            </a>
        </aside>

        <section>
            <nav>
                <ul>
                    <li>
                        <span>
                        <div class="btn-group">
                            <button type="button" class="btn btn-success ">{{ sort }}</button>
                            <button type="button" class="btn btn-success dropdown-toggle " data-toggle="dropdown"
                                    aria-haspopup="true" aria-expanded="false">
                                <span class="glyphicon glyphicon-chevron-down"></span>
                            </button>
                            <ul class="dropdown-menu" id="all_sort">
                                <li style="width:5.0rem;margin-bottom: 0.05rem;"><a
                                        href="{% url 'App:publishertask' typeid 0 %}"
                                        class="list-group-item list-group-item-success" id="酬劳">酬劳</a></li>
                                <li style="width:5.0rem;margin-bottom: 0.05rem"><a
                                        href="{% url 'App:publishertask' typeid 1 %}"
                                        class="list-group-item list-group-item-success" id="截止日期">截止日期</a></li>
                                <li style="width:5.0rem;"><a
                                        href="{% url 'App:publishertask' typeid 4 %}"
                                        class="list-group-item list-group-item-success" id="所有任务">所有任务</a></li>
                            </ul>
                        </div>
                        </span>
                    </li>
                </ul>
            </nav>
            <menu>
                <ul>
                    {% for task in task_list %}
                        <li>
                            <a href="{% url 'App:taskcontent'  task.id %}" class="list-group-item">
                                <h4 class="list-group-item-heading" style="color: darkorange;display: inline-block;
                                text-align: center;vertical-align: center;line-height: 0.4rem;font-weight: 800;">
                                    {{ task.task_name }}</h4><!--border: 1px solid orange; border-radius: 1000px;-->
                                <div class="list-group-item-text">
                                    <div>
                                        详情：{{ task.task_sketch }}
                                    </div>
                                    <div style="float: left;display: inline">
                                        酬劳：￥{{ task.task_reward }}
                                        <br>
                                        联系人：{{ task.publisher.username }}
                                    </div>

                                    <div style="font-size: 6px;float: left;display: inline;margin-top: 0.5rem">
                                        截止日期：{{ task.task_date_year }}年{{ task.task_date_month }}月{{ task.task_date_month }}日
                                    </div>

                                    <div>
                                        {% if task.is_finished %}
                                            <h1 style="color: red;border:1px solid red;border-radius: 1500px;display:inline-block;position: absolute;right: 0.15rem;">
                                                已完成</h1>
                                        {% else %}
                                            <h1 style="color: green;border:1px solid green;border-radius: 1500px;display: inline-block;position: absolute;right: 0.15rem;margin-top: -0.5rem;">
                                                未完成</h1>
                                            <button class="btn-danger" onclick="relievetask({{ task.id }})" style="position: absolute;right:0.15rem;">解除委托</button>
                                            <button class="btn-success" onclick="finishtask({{ task.id }})" style="position: absolute;right:0.15rem;margin-top: 0.5rem">任务完成</button>

                                        {% endif %}
                                    </div>
                                </div>
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </menu>

        </section>
    </div>
{% endblock %}

schoolmate helper/schoolmates_helper/templates/user/receive.html
<h4>Dear {{ username_publisher }}:</h4>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    您任务编号为{{ task_id }}的任务"{{ task_name }}"已被{{ username_hunter }}接受，请及时通过邮箱:{{ email }}与其取得联系。
    祝任务过程愉快！
</p>
<h6>最好的时光，与你共享</h6>
<h6>by:Schoolmates Helper Team</h6>

schoolmate helper/schoolmates_helper/templates/user/relieve.html
<h4>Dear {{ username_hunter }}:</h4>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    您接取的任务编号为{{ task_id }}的任务"{{ task_name }}"已被{{ username_publisher }}解除委托，请继续接取其他任务。
</p>
<h6>最好的时光，与你共享</h6>
<h6>by:Schoolmates Helper Team</h6>