schoolmates_helper/App/urls.py
# _*_ coding: utf-8 _*_
# 开发团队：软件工程第5组
# 开发人员：莨瑾
# 开发时间：2020/3/20 16:15
# 文件名称: urls.py
# 开发工具：PyCharm
from django.urls import path

from App import views

urlpatterns = [
    path('home/', views.home, name='home'),
    path('alltask/', views.alltask, name='alltask'),
    path('alltaskwithparams/<int:typeid>', views.alltask_with_params, name='alltask_with_params'),
    path('alltasksort/<int:typeid>/<slug:typesort1>/<slug:typesort2>/<slug:typesort3>', views.alltask_sort,
         name='alltask_sort'),

    path('task/', views.task, name='task'),
    path('mine/', views.mine, name='mine'),

    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('checkuser/', views.checkuser, name='checkuser'),
    path('checkemail/', views.checkemail, name='checkemail'),
    path('checklogin/', views.checklogin, name='checklogin'),

    path('logout/', views.logout, name='logout'),

    path('activate/', views.activate, name='activate'),

    path('sendemail/', views.sendemail, name='send_email'),

    path('receivetask/', views.receivetask, name='receivetask'),
    path('relievetask/', views.relievetask, name='relievetask'),
    path('relievetask2/', views.relievetask2, name='relievetask2'),
    path('finishtask/', views.finishtask, name='finishtask'),

    path('aboutus/', views.aboutus, name='aboutus'),
    path('callus/', views.callus, name='callus'),

    path('alltaskpublisher/', views.alltaskpublisher, name='alltaskpublisher'),
    path('alltaskpublisherwithparams/<int:typeid>/', views.alltaskpublisher_with_params,
         name='alltaskpublisher_with_params'),
    path('alltaskpublishersort/<int:typeid>/<int:sort_way>/',
         views.alltaskpublisher_sort, name='alltaskpublisher_sort'),

    path('alltaskhunter/', views.alltaskhunter, name='alltaskhunter'),
    path('alltaskhunterwithparams/<int:typeid>/', views.alltaskhunter_with_params,
         name='alltaskhunter_with_params'),
    path('alltaskhuntersort/<int:typeid>/<int:sort_way>/',
         views.alltaskhunter_sort, name='alltaskhunter_sort'),

    path('huntertask/<int:typeid>/<int:sort_way>/', views.huntertask, name='huntertask'),
    path('publishertask/<int:typeid>/<int:sort_way>/', views.publishertask, name='publishertask'),
    path('taskfinished/<int:typeid>/<int:sort_way>/', views.taskfinished, name='taskfinished'),
    path('comment/<int:typeid>/<int:sort_way>/', views.comment, name='comment'),
    path('taskcontent/<int:task_id>/', views.taskcontent, name='taskcontent'),

    path('modifyuser/', views.modifyuser, name='modifyuser'),
    path('modifytask/<int:task_id>/', views.modifytask, name='modifytask'),
]

schoolmates_helper/schoolmates_helper/urls.py
from django.contrib import admin
from django.urls import path, include

from schoolmates_helper import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home),
    path('App/', include(('App.urls', 'App'), namespace='App')),
    path('task_square/', include('tasks_square.urls')),
    path('task_received/', include('task_received.urls')),
    path('hunt/', include(('hunt.urls', 'hunt'), namespace='hunt')),
    path('task_released/', include('task_released.urls')),
]

schoolmates_helper/task_received/urls.py
from django.urls import path
from . import views

app_name = 'task_received'
urlpatterns = [
    path('', views.index, name='index'),
    path('all_task_received/', views.all_task_received, name='all_task_received'),
    path('<int:task_id>/task_revoke/', views.task_revoke, name='task_revoke'),
    path('<int:task_id>/task_revoke/reasons/', views.reasons_revoke, name='reasons_revoke'),
    path('<int:task_id>/task_detail', views.task_detail, name='task_detail'),
    path('<int:task_id>/task_finished', views.task_finished, name='task_finished'),
    path('all_task_received/<int:tasktype_id>/', views.task_sometype, name='task_sometype'),
    path('received_tasks_finished/', views.received_tasks_finished, name='received_tasks_finished'),
    path('received_tasks_finished/<int:tasktype_id>/', views.task_sometype_finished, name='task_sometype_finished'),
    path('received_tasks_not_finished/', views.received_tasks_not_finished, name='received_tasks_not_finished'),
    path('received_tasks_not_finished/<int:tasktype_id>', views.task_sometype_not_finished,
         name='task_sometype_not_finished'),
    # 2020年4月25日 swf 新增
    path('comment/',views.comment,name='comment'),
    path('revoke/',views.revoke,name='revoke'),
    # 2020年4月30日 swf 新增
    path('logout/',views.logout,name='logout'),
]

schoolmates_helper/templates/allhome.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>主页</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
</head>
<body style="margin:0;padding:0;background: url(/static/img/background.png);background-size:cover;">
<div>
    <a onclick="window.location.href='{% url 'App:home' %}'" >
        <button class="btn-group-lg" style="font-size: 10rem;margin-top: 2rem;margin-left: 8rem;background:transparent;border-width:0;outline:none;">
            <span class="glyphicon glyphicon-phone"></span>点击进入手机端
        </button>
    </a>
    <a href={% url 'task_received:logout' %}>
        <button class="btn-group-lg" style="font-size: 10rem;margin: 8rem;background:transparent;border-width:0;outline:none;">
            <span class="glyphicon glyphicon-blackboard"></span>点击进入电脑端
        </button>
    </a>


</div>
</body>
</html>

schoolmates_helper/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/swiper.css' %}">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    {% block ext_css %}
    
    {% endblock %}
</head>
<body>
   {% block header %}
   
   {% endblock %}

   {% block content %}

   {% endblock %}

   {% block footer %}

   {% endblock %}
   <script type="text/javascript" src="{% static 'js/jquery.js'  %}"></script>
   <script type="text/javascript" src="{% static 'js/bootstrap.js'  %}"></script>
   <script type="text/javascript" src="{% static 'js/base.js'  %}"></script>
   {% block ext_js %}
    
   {% endblock %}
</body>
</html>

schoolmates_helper/templates/base_main.html
{% extends 'base.html' %}

{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'Schoolmateshelper/main/css/main.css' %}">
{% endblock %}
{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'Schoolmateshelper/user/js/base_main.js' %}"></script>
{% endblock %}
{% block header %}
    <header></header>
{% endblock %}

{% block footer %}
    <footer>
        <a href="{% url 'App:home' %}" class="home">
            <dl>
                <dt>
                    <span></span>
                </dt>
                <dd>首页</dd>
            </dl>
        </a>
        <a href="{% url 'App:alltask' %}" class="alltask">
            <dl>
                <dt>
                    <span></span>
                </dt>
                <dd>任务广场</dd>
            </dl>
        </a>
        <a href="#" class="task" onclick="on_click_base_main({{ is_login }},{{ is_activate }})">
            <dl>
                <dt>
                    <span></span>
                </dt>
                <dd>发布任务</dd>
            </dl>
        </a>
        <a href="{% url 'App:mine' %}" class="mine_icon">
            <dl>
                <dt>
                    <span></span>
                </dt>
                <dd>个人主页</dd>
            </dl>
        </a>
    </footer>
{% endblock %}

schoolmates_helper/templates/base_user.html
{% extends 'base.html' %}
{% load static %}



{% block ext_css %}
   {{ block.super }}
    <link rel="stylesheet" href="{% static 'Schoolmateshelper/user/css/user.css' %}">
{% endblock %}

{% block header %}
    <header></header>
{% endblock %}